name: Serverless CI/CD

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Deploy to AWS CloudFormation
      run: |
        aws cloudformation deploy \
          --template-file aws_cloudformation_template.yml \
          --stack-name bits-devops \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM

